compat: Fix so main works again on python3.4
Apparently importlib.util.spec_from_file_location did exist, but
importlib.util.module_from_spec did not. Caused this on Python 3.4:

    Traceback (most recent call last):
      File "bin/asterisklint", line 34, in <module>
        sys.exit(main(sys.argv[1:], os.environ))
      File "asterisklint/main.py", line 170, in main
        command_module = load_command(command)
      File "asterisklint/main.py", line 138, in load_command
        command_module = importlib.util.module_from_spec(spec)
    AttributeError: 'module' object has no attribute 'module_from_spec'